version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=supersecret
    volumes:
      - ./backend:/app  # Syncs backend folder with container
      - /app/node_modules  # Prevents overwriting container-installed dependencies
    command: npm run start:dev  # Use nodemon to auto-restart on changes

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Sync frontend folder
      - /app/node_modules  # Prevents overwriting container-installed dependencies
    command: npm start
