services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=supersecret

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend


