name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (needed for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Cache Docker layers to speed up build
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ishubishu/my-fullstack-app:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push ishubishu/my-fullstack-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Checkout code again (for the deploy step)
    - name: Checkout code
      uses: actions/checkout@v2

    # Deploy your application (Example: using SSH to deploy to a server)
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /path/to/your/app
          docker pull ishubishu/my-fullstack-app:latest
          docker-compose down
          docker-compose up -d
        EOF
